#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchStore.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WatchStore")]
	public partial class dbDongHoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBill(Bill instance);
    partial void UpdateBill(Bill instance);
    partial void DeleteBill(Bill instance);
    partial void InsertBillDetail(BillDetail instance);
    partial void UpdateBillDetail(BillDetail instance);
    partial void DeleteBillDetail(BillDetail instance);
    partial void InsertBrand(Brand instance);
    partial void UpdateBrand(Brand instance);
    partial void DeleteBrand(Brand instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertOrigin(Origin instance);
    partial void UpdateOrigin(Origin instance);
    partial void DeleteOrigin(Origin instance);
    partial void InsertProductFor(ProductFor instance);
    partial void UpdateProductFor(ProductFor instance);
    partial void DeleteProductFor(ProductFor instance);
    partial void InsertStaff(Staff instance);
    partial void UpdateStaff(Staff instance);
    partial void DeleteStaff(Staff instance);
    partial void InsertSupplier(Supplier instance);
    partial void UpdateSupplier(Supplier instance);
    partial void DeleteSupplier(Supplier instance);
    partial void InsertWatch(Watch instance);
    partial void UpdateWatch(Watch instance);
    partial void DeleteWatch(Watch instance);
    #endregion
		
		public dbDongHoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDongHoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDongHoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDongHoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bill> Bills
		{
			get
			{
				return this.GetTable<Bill>();
			}
		}
		
		public System.Data.Linq.Table<BillDetail> BillDetails
		{
			get
			{
				return this.GetTable<BillDetail>();
			}
		}
		
		public System.Data.Linq.Table<Brand> Brands
		{
			get
			{
				return this.GetTable<Brand>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Origin> Origins
		{
			get
			{
				return this.GetTable<Origin>();
			}
		}
		
		public System.Data.Linq.Table<ProductFor> ProductFors
		{
			get
			{
				return this.GetTable<ProductFor>();
			}
		}
		
		public System.Data.Linq.Table<Staff> Staffs
		{
			get
			{
				return this.GetTable<Staff>();
			}
		}
		
		public System.Data.Linq.Table<Supplier> Suppliers
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Watch> Watches
		{
			get
			{
				return this.GetTable<Watch>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AUTO_IDCustomer", IsComposable=true)]
		public string AUTO_IDCustomer()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AUTO_IDAcountCustomer", IsComposable=true)]
		public string AUTO_IDAcountCustomer()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AUTO_IDAcountStaff", IsComposable=true)]
		public string AUTO_IDAcountStaff()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AUTO_IDStaff", IsComposable=true)]
		public string AUTO_IDStaff()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AUTO_IDWatch", IsComposable=true)]
		public string AUTO_IDWatch()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bill")]
	public partial class Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBill;
		
		private System.DateTime _Time;
		
		private bool _Status;
		
		private string _IDCustomer;
		
		private EntitySet<BillDetail> _BillDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBillChanging(int value);
    partial void OnIDBillChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnIDCustomerChanging(string value);
    partial void OnIDCustomerChanged();
    #endregion
		
		public Bill()
		{
			this._BillDetails = new EntitySet<BillDetail>(new Action<BillDetail>(this.attach_BillDetails), new Action<BillDetail>(this.detach_BillDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBill", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBill
		{
			get
			{
				return this._IDBill;
			}
			set
			{
				if ((this._IDBill != value))
				{
					this.OnIDBillChanging(value);
					this.SendPropertyChanging();
					this._IDBill = value;
					this.SendPropertyChanged("IDBill");
					this.OnIDBillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCustomer", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string IDCustomer
		{
			get
			{
				return this._IDCustomer;
			}
			set
			{
				if ((this._IDCustomer != value))
				{
					this.OnIDCustomerChanging(value);
					this.SendPropertyChanging();
					this._IDCustomer = value;
					this.SendPropertyChanged("IDCustomer");
					this.OnIDCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bill_BillDetail", Storage="_BillDetails", ThisKey="IDBill", OtherKey="IDBill")]
		public EntitySet<BillDetail> BillDetails
		{
			get
			{
				return this._BillDetails;
			}
			set
			{
				this._BillDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BillDetails(BillDetail entity)
		{
			this.SendPropertyChanging();
			entity.Bill = this;
		}
		
		private void detach_BillDetails(BillDetail entity)
		{
			this.SendPropertyChanging();
			entity.Bill = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BillDetails")]
	public partial class BillDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDWatch;
		
		private int _IDBill;
		
		private int _NumberOfOrders;
		
		private EntityRef<Bill> _Bill;
		
		private EntityRef<Watch> _Watch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDWatchChanging(string value);
    partial void OnIDWatchChanged();
    partial void OnIDBillChanging(int value);
    partial void OnIDBillChanged();
    partial void OnNumberOfOrdersChanging(int value);
    partial void OnNumberOfOrdersChanged();
    #endregion
		
		public BillDetail()
		{
			this._Bill = default(EntityRef<Bill>);
			this._Watch = default(EntityRef<Watch>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWatch", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDWatch
		{
			get
			{
				return this._IDWatch;
			}
			set
			{
				if ((this._IDWatch != value))
				{
					if (this._Watch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDWatchChanging(value);
					this.SendPropertyChanging();
					this._IDWatch = value;
					this.SendPropertyChanged("IDWatch");
					this.OnIDWatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBill", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBill
		{
			get
			{
				return this._IDBill;
			}
			set
			{
				if ((this._IDBill != value))
				{
					if (this._Bill.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBillChanging(value);
					this.SendPropertyChanging();
					this._IDBill = value;
					this.SendPropertyChanged("IDBill");
					this.OnIDBillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfOrders", DbType="Int NOT NULL")]
		public int NumberOfOrders
		{
			get
			{
				return this._NumberOfOrders;
			}
			set
			{
				if ((this._NumberOfOrders != value))
				{
					this.OnNumberOfOrdersChanging(value);
					this.SendPropertyChanging();
					this._NumberOfOrders = value;
					this.SendPropertyChanged("NumberOfOrders");
					this.OnNumberOfOrdersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bill_BillDetail", Storage="_Bill", ThisKey="IDBill", OtherKey="IDBill", IsForeignKey=true)]
		public Bill Bill
		{
			get
			{
				return this._Bill.Entity;
			}
			set
			{
				Bill previousValue = this._Bill.Entity;
				if (((previousValue != value) 
							|| (this._Bill.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bill.Entity = null;
						previousValue.BillDetails.Remove(this);
					}
					this._Bill.Entity = value;
					if ((value != null))
					{
						value.BillDetails.Add(this);
						this._IDBill = value.IDBill;
					}
					else
					{
						this._IDBill = default(int);
					}
					this.SendPropertyChanged("Bill");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Watch_BillDetail", Storage="_Watch", ThisKey="IDWatch", OtherKey="IDWatch", IsForeignKey=true)]
		public Watch Watch
		{
			get
			{
				return this._Watch.Entity;
			}
			set
			{
				Watch previousValue = this._Watch.Entity;
				if (((previousValue != value) 
							|| (this._Watch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Watch.Entity = null;
						previousValue.BillDetails.Remove(this);
					}
					this._Watch.Entity = value;
					if ((value != null))
					{
						value.BillDetails.Add(this);
						this._IDWatch = value.IDWatch;
					}
					else
					{
						this._IDWatch = default(string);
					}
					this.SendPropertyChanged("Watch");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Brand")]
	public partial class Brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBrand;
		
		private string _NameBrand;
		
		private EntitySet<Watch> _Watches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBrandChanging(int value);
    partial void OnIDBrandChanged();
    partial void OnNameBrandChanging(string value);
    partial void OnNameBrandChanged();
    #endregion
		
		public Brand()
		{
			this._Watches = new EntitySet<Watch>(new Action<Watch>(this.attach_Watches), new Action<Watch>(this.detach_Watches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBrand", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBrand
		{
			get
			{
				return this._IDBrand;
			}
			set
			{
				if ((this._IDBrand != value))
				{
					this.OnIDBrandChanging(value);
					this.SendPropertyChanging();
					this._IDBrand = value;
					this.SendPropertyChanged("IDBrand");
					this.OnIDBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameBrand", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string NameBrand
		{
			get
			{
				return this._NameBrand;
			}
			set
			{
				if ((this._NameBrand != value))
				{
					this.OnNameBrandChanging(value);
					this.SendPropertyChanging();
					this._NameBrand = value;
					this.SendPropertyChanged("NameBrand");
					this.OnNameBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Brand_Watch", Storage="_Watches", ThisKey="IDBrand", OtherKey="IDBrand")]
		public EntitySet<Watch> Watches
		{
			get
			{
				return this._Watches;
			}
			set
			{
				this._Watches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Brand = this;
		}
		
		private void detach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Brand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDCustomer;
		
		private string _FullName;
		
		private string _Gender;
		
		private string _CitizenIdentification;
		
		private string _Address;
		
		private string _Id;
		
		private int _IDAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCustomerChanging(string value);
    partial void OnIDCustomerChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnCitizenIdentificationChanging(string value);
    partial void OnCitizenIdentificationChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIDAPChanging(int value);
    partial void OnIDAPChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCustomer", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDCustomer
		{
			get
			{
				return this._IDCustomer;
			}
			set
			{
				if ((this._IDCustomer != value))
				{
					this.OnIDCustomerChanging(value);
					this.SendPropertyChanging();
					this._IDCustomer = value;
					this.SendPropertyChanged("IDCustomer");
					this.OnIDCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CitizenIdentification", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CitizenIdentification
		{
			get
			{
				return this._CitizenIdentification;
			}
			set
			{
				if ((this._CitizenIdentification != value))
				{
					this.OnCitizenIdentificationChanging(value);
					this.SendPropertyChanging();
					this._CitizenIdentification = value;
					this.SendPropertyChanged("CitizenIdentification");
					this.OnCitizenIdentificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAP", DbType="Int NOT NULL")]
		public int IDAP
		{
			get
			{
				return this._IDAP;
			}
			set
			{
				if ((this._IDAP != value))
				{
					this.OnIDAPChanging(value);
					this.SendPropertyChanging();
					this._IDAP = value;
					this.SendPropertyChanged("IDAP");
					this.OnIDAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Origin")]
	public partial class Origin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDOrigin;
		
		private string _NameOrigin;
		
		private EntitySet<Watch> _Watches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDOriginChanging(int value);
    partial void OnIDOriginChanged();
    partial void OnNameOriginChanging(string value);
    partial void OnNameOriginChanged();
    #endregion
		
		public Origin()
		{
			this._Watches = new EntitySet<Watch>(new Action<Watch>(this.attach_Watches), new Action<Watch>(this.detach_Watches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOrigin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDOrigin
		{
			get
			{
				return this._IDOrigin;
			}
			set
			{
				if ((this._IDOrigin != value))
				{
					this.OnIDOriginChanging(value);
					this.SendPropertyChanging();
					this._IDOrigin = value;
					this.SendPropertyChanged("IDOrigin");
					this.OnIDOriginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOrigin", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string NameOrigin
		{
			get
			{
				return this._NameOrigin;
			}
			set
			{
				if ((this._NameOrigin != value))
				{
					this.OnNameOriginChanging(value);
					this.SendPropertyChanging();
					this._NameOrigin = value;
					this.SendPropertyChanged("NameOrigin");
					this.OnNameOriginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Origin_Watch", Storage="_Watches", ThisKey="IDOrigin", OtherKey="IDOrigin")]
		public EntitySet<Watch> Watches
		{
			get
			{
				return this._Watches;
			}
			set
			{
				this._Watches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Origin = this;
		}
		
		private void detach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Origin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductFor")]
	public partial class ProductFor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDProductFor;
		
		private string _NameProductFor;
		
		private EntitySet<Watch> _Watches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDProductForChanging(int value);
    partial void OnIDProductForChanged();
    partial void OnNameProductForChanging(string value);
    partial void OnNameProductForChanged();
    #endregion
		
		public ProductFor()
		{
			this._Watches = new EntitySet<Watch>(new Action<Watch>(this.attach_Watches), new Action<Watch>(this.detach_Watches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProductFor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDProductFor
		{
			get
			{
				return this._IDProductFor;
			}
			set
			{
				if ((this._IDProductFor != value))
				{
					this.OnIDProductForChanging(value);
					this.SendPropertyChanging();
					this._IDProductFor = value;
					this.SendPropertyChanged("IDProductFor");
					this.OnIDProductForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameProductFor", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NameProductFor
		{
			get
			{
				return this._NameProductFor;
			}
			set
			{
				if ((this._NameProductFor != value))
				{
					this.OnNameProductForChanging(value);
					this.SendPropertyChanging();
					this._NameProductFor = value;
					this.SendPropertyChanged("NameProductFor");
					this.OnNameProductForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductFor_Watch", Storage="_Watches", ThisKey="IDProductFor", OtherKey="IDProductFor")]
		public EntitySet<Watch> Watches
		{
			get
			{
				return this._Watches;
			}
			set
			{
				this._Watches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.ProductFor = this;
		}
		
		private void detach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.ProductFor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff")]
	public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDStaff;
		
		private string _FullName;
		
		private string _Gender;
		
		private string _CitizenIdentification;
		
		private string _Address;
		
		private string _Id;
		
		private int _IDAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDStaffChanging(string value);
    partial void OnIDStaffChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnCitizenIdentificationChanging(string value);
    partial void OnCitizenIdentificationChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIDAPChanging(int value);
    partial void OnIDAPChanged();
    #endregion
		
		public Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStaff", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDStaff
		{
			get
			{
				return this._IDStaff;
			}
			set
			{
				if ((this._IDStaff != value))
				{
					this.OnIDStaffChanging(value);
					this.SendPropertyChanging();
					this._IDStaff = value;
					this.SendPropertyChanged("IDStaff");
					this.OnIDStaffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CitizenIdentification", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CitizenIdentification
		{
			get
			{
				return this._CitizenIdentification;
			}
			set
			{
				if ((this._CitizenIdentification != value))
				{
					this.OnCitizenIdentificationChanging(value);
					this.SendPropertyChanging();
					this._CitizenIdentification = value;
					this.SendPropertyChanged("CitizenIdentification");
					this.OnCitizenIdentificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAP", DbType="Int NOT NULL")]
		public int IDAP
		{
			get
			{
				return this._IDAP;
			}
			set
			{
				if ((this._IDAP != value))
				{
					this.OnIDAPChanging(value);
					this.SendPropertyChanging();
					this._IDAP = value;
					this.SendPropertyChanged("IDAP");
					this.OnIDAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supplier")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDSupplier;
		
		private string _NameSupplier;
		
		private string _Adress;
		
		private string _PhoneNumber;
		
		private EntitySet<Watch> _Watches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSupplierChanging(int value);
    partial void OnIDSupplierChanged();
    partial void OnNameSupplierChanging(string value);
    partial void OnNameSupplierChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public Supplier()
		{
			this._Watches = new EntitySet<Watch>(new Action<Watch>(this.attach_Watches), new Action<Watch>(this.detach_Watches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSupplier", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDSupplier
		{
			get
			{
				return this._IDSupplier;
			}
			set
			{
				if ((this._IDSupplier != value))
				{
					this.OnIDSupplierChanging(value);
					this.SendPropertyChanging();
					this._IDSupplier = value;
					this.SendPropertyChanged("IDSupplier");
					this.OnIDSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameSupplier", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NameSupplier
		{
			get
			{
				return this._NameSupplier;
			}
			set
			{
				if ((this._NameSupplier != value))
				{
					this.OnNameSupplierChanging(value);
					this.SendPropertyChanging();
					this._NameSupplier = value;
					this.SendPropertyChanged("NameSupplier");
					this.OnNameSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="NVarChar(290) NOT NULL", CanBeNull=false)]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Watch", Storage="_Watches", ThisKey="IDSupplier", OtherKey="IDSupplier")]
		public EntitySet<Watch> Watches
		{
			get
			{
				return this._Watches;
			}
			set
			{
				this._Watches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = this;
		}
		
		private void detach_Watches(Watch entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Watch")]
	public partial class Watch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDWatch;
		
		private string _NameWatch;
		
		private int _IDSupplier;
		
		private int _IDBrand;
		
		private int _IDOrigin;
		
		private string _Image;
		
		private decimal _Price;
		
		private bool _Status;
		
		private int _IDProductFor;
		
		private string _Content;
		
		private EntitySet<BillDetail> _BillDetails;
		
		private EntityRef<Brand> _Brand;
		
		private EntityRef<Origin> _Origin;
		
		private EntityRef<ProductFor> _ProductFor;
		
		private EntityRef<Supplier> _Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDWatchChanging(string value);
    partial void OnIDWatchChanged();
    partial void OnNameWatchChanging(string value);
    partial void OnNameWatchChanged();
    partial void OnIDSupplierChanging(int value);
    partial void OnIDSupplierChanged();
    partial void OnIDBrandChanging(int value);
    partial void OnIDBrandChanged();
    partial void OnIDOriginChanging(int value);
    partial void OnIDOriginChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnIDProductForChanging(int value);
    partial void OnIDProductForChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    #endregion
		
		public Watch()
		{
			this._BillDetails = new EntitySet<BillDetail>(new Action<BillDetail>(this.attach_BillDetails), new Action<BillDetail>(this.detach_BillDetails));
			this._Brand = default(EntityRef<Brand>);
			this._Origin = default(EntityRef<Origin>);
			this._ProductFor = default(EntityRef<ProductFor>);
			this._Supplier = default(EntityRef<Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDWatch", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDWatch
		{
			get
			{
				return this._IDWatch;
			}
			set
			{
				if ((this._IDWatch != value))
				{
					this.OnIDWatchChanging(value);
					this.SendPropertyChanging();
					this._IDWatch = value;
					this.SendPropertyChanged("IDWatch");
					this.OnIDWatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameWatch", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NameWatch
		{
			get
			{
				return this._NameWatch;
			}
			set
			{
				if ((this._NameWatch != value))
				{
					this.OnNameWatchChanging(value);
					this.SendPropertyChanging();
					this._NameWatch = value;
					this.SendPropertyChanged("NameWatch");
					this.OnNameWatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSupplier", DbType="Int NOT NULL")]
		public int IDSupplier
		{
			get
			{
				return this._IDSupplier;
			}
			set
			{
				if ((this._IDSupplier != value))
				{
					if (this._Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSupplierChanging(value);
					this.SendPropertyChanging();
					this._IDSupplier = value;
					this.SendPropertyChanged("IDSupplier");
					this.OnIDSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBrand", DbType="Int NOT NULL")]
		public int IDBrand
		{
			get
			{
				return this._IDBrand;
			}
			set
			{
				if ((this._IDBrand != value))
				{
					if (this._Brand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBrandChanging(value);
					this.SendPropertyChanging();
					this._IDBrand = value;
					this.SendPropertyChanged("IDBrand");
					this.OnIDBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOrigin", DbType="Int NOT NULL")]
		public int IDOrigin
		{
			get
			{
				return this._IDOrigin;
			}
			set
			{
				if ((this._IDOrigin != value))
				{
					if (this._Origin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDOriginChanging(value);
					this.SendPropertyChanging();
					this._IDOrigin = value;
					this.SendPropertyChanged("IDOrigin");
					this.OnIDOriginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProductFor", DbType="Int NOT NULL")]
		public int IDProductFor
		{
			get
			{
				return this._IDProductFor;
			}
			set
			{
				if ((this._IDProductFor != value))
				{
					if (this._ProductFor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDProductForChanging(value);
					this.SendPropertyChanging();
					this._IDProductFor = value;
					this.SendPropertyChanged("IDProductFor");
					this.OnIDProductForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(1500)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Watch_BillDetail", Storage="_BillDetails", ThisKey="IDWatch", OtherKey="IDWatch")]
		public EntitySet<BillDetail> BillDetails
		{
			get
			{
				return this._BillDetails;
			}
			set
			{
				this._BillDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Brand_Watch", Storage="_Brand", ThisKey="IDBrand", OtherKey="IDBrand", IsForeignKey=true)]
		public Brand Brand
		{
			get
			{
				return this._Brand.Entity;
			}
			set
			{
				Brand previousValue = this._Brand.Entity;
				if (((previousValue != value) 
							|| (this._Brand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Brand.Entity = null;
						previousValue.Watches.Remove(this);
					}
					this._Brand.Entity = value;
					if ((value != null))
					{
						value.Watches.Add(this);
						this._IDBrand = value.IDBrand;
					}
					else
					{
						this._IDBrand = default(int);
					}
					this.SendPropertyChanged("Brand");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Origin_Watch", Storage="_Origin", ThisKey="IDOrigin", OtherKey="IDOrigin", IsForeignKey=true)]
		public Origin Origin
		{
			get
			{
				return this._Origin.Entity;
			}
			set
			{
				Origin previousValue = this._Origin.Entity;
				if (((previousValue != value) 
							|| (this._Origin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Origin.Entity = null;
						previousValue.Watches.Remove(this);
					}
					this._Origin.Entity = value;
					if ((value != null))
					{
						value.Watches.Add(this);
						this._IDOrigin = value.IDOrigin;
					}
					else
					{
						this._IDOrigin = default(int);
					}
					this.SendPropertyChanged("Origin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductFor_Watch", Storage="_ProductFor", ThisKey="IDProductFor", OtherKey="IDProductFor", IsForeignKey=true)]
		public ProductFor ProductFor
		{
			get
			{
				return this._ProductFor.Entity;
			}
			set
			{
				ProductFor previousValue = this._ProductFor.Entity;
				if (((previousValue != value) 
							|| (this._ProductFor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductFor.Entity = null;
						previousValue.Watches.Remove(this);
					}
					this._ProductFor.Entity = value;
					if ((value != null))
					{
						value.Watches.Add(this);
						this._IDProductFor = value.IDProductFor;
					}
					else
					{
						this._IDProductFor = default(int);
					}
					this.SendPropertyChanged("ProductFor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Watch", Storage="_Supplier", ThisKey="IDSupplier", OtherKey="IDSupplier", IsForeignKey=true)]
		public Supplier Supplier
		{
			get
			{
				return this._Supplier.Entity;
			}
			set
			{
				Supplier previousValue = this._Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Supplier.Entity = null;
						previousValue.Watches.Remove(this);
					}
					this._Supplier.Entity = value;
					if ((value != null))
					{
						value.Watches.Add(this);
						this._IDSupplier = value.IDSupplier;
					}
					else
					{
						this._IDSupplier = default(int);
					}
					this.SendPropertyChanged("Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BillDetails(BillDetail entity)
		{
			this.SendPropertyChanging();
			entity.Watch = this;
		}
		
		private void detach_BillDetails(BillDetail entity)
		{
			this.SendPropertyChanging();
			entity.Watch = null;
		}
	}
}
#pragma warning restore 1591
